Repository Gyeongdan/gyeongdan-server-fastapi, pull requests merged in 2024-07, with the labels that each got.

#44 기사 재생성 프롬프트 엔지니어링
  app/model/prompt/prompt_version.py
  app/model/prompt/simple_article/2024-07-02.txt
  app/service/simple_article_service.py
Labels: Feature

#50 크롤링 오류 수정
  app/model/article_publisher.py
  app/service/crawl_article_service.py
Labels: Bug

#51 articles_router 삭제
  app/main.py
  app/router/article_crud_router.py
Labels: Ship

#48 기사 크롤링 및 변환 스케쥴링
  Pipfile
  Pipfile.lock
  app/main.py
  app/model/article_publisher.py
  app/service/news_scheduling_service.py
  app/service/simple_article_service.py
Labels: Feature

#53 프롬프트 및 DTO 변경에 따른 Validation 및 저장 로직 수정
  app/model/crawled_article.py
  app/model/prompt/simple_article/2024-07-02.txt
  app/model/simplified_article.py
  app/router/generate_simple_article_router.py
  app/service/article_manage_service.py
  app/service/simple_article_service.py
Labels: Feature

#54 Docker File 생성 및 ECS 배포 테스트
  .github/workflows/deploy-ecs.yml
  Dockerfile
  Pipfile
  Pipfile.lock
  entrypoint.sh
Labels: Feature

#61 공공데이터를 활용해서 칼럼 재생성 구현
  app/model/prompt/prompt_version.py
  app/model/prompt/public_data_api_article/2024-07-05.txt
  app/service/public_data_api_service.py
  app/service/public_data_article_service.py
Labels: Feature

#65 CICD 구축
  .github/workflows/deploy-ecs.yml
  tf-staging.json
Labels: Feature

#55 메일 내용 생성 및 송신 기능 연결
  app/model/newsletter_article.py
  app/model/prompt/newsletter_article/2024-07-03.txt
  app/model/prompt/prompt_version.py
  app/repository/newsletter_article_crud.py
  app/router/newsletter_article_crud_router.py
  app/router/send_email_service_router.py
  app/service/newsletter_article_service.py
Labels: Feature

#71 staging과 staging db 연결
  .github/workflows/deploy-ecs.yml
  Dockerfile
  app/database/session.py
  app/model/crawled_article.py
  app/model/prompt/simple_article/2024-07-02.txt
Labels: Feature

#72 크롤링 스케쥴링 세션 문제 해결
  app/database/repository.py
  app/database/session.py
  app/main.py
  app/model/prompt/simple_article/2024-07-02.txt
  app/router/news_scrap_router.py
  app/service/news_scheduling_service.py
Labels: Bug

#74 추천 시스템 구현
  Dockerfile
  Pipfile
  Pipfile.lock
  app/model/crawled_article.py
  app/model/interaction.py
  app/recommend/recommend_service.py
  app/recommend/user_classification.csv
  app/repository/crawled_article_crud.py
  app/repository/interaction_crud.py
Labels: Feature

#76 추천시스템 관련 간단한 refactoring
  app/model/crawled_article.py
  app/recommend/recommend_service.py
  app/repository/crawled_article_crud.py
Labels: Ship

#78 기사 생성 고도화 작업(RAG & LangChain)
  .pylintrc
  Pipfile
  Pipfile.lock
  app/articles/__init__.py
  app/articles/rag_lang_chain/__init__.py
  app/articles/rag_lang_chain/chromadb_manager.py
  app/articles/rag_lang_chain/google_cse_retriver.py
  app/articles/rag_lang_chain/google_search_api.py
  app/articles/rag_lang_chain/langchain_applied.py
  app/articles/rag_lang_chain/wekipedia_api.py
Labels: Enhancement

#80 공공 api 활용한 데이터 시각화
  app/model/prompt/graphic_article/2024-07-10.txt
  app/model/prompt/prompt_version.py
  app/service/api_visualization_service.py
Labels: Feature

#84 유저 분류 질문, 응답으로 분류 나누기
  app/main.py
  app/model/user_type.py
  app/repository/user_type_crud.py
  app/router/user_type_router.py
  app/service/user_type_service.py
Labels: Feature

#85 기사 재생성 스케쥴링 RAG/LangChain 마이그레이션
  app/articles/rag_lang_chain/__init__.py
  app/articles/rag_lang_chain/google_cse_retriver.py
  app/articles/rag_lang_chain/google_search_api.py
  app/articles/rag_lang_chain/langchain_applied.py
  app/articles/rag_lang_chain/wekipedia_api.py
  app/model/prompt/prompt_version.py
  app/model/prompt/simple_article/2024-07-14.txt
  app/rag_lang_chain/__init__.py
  app/rag_lang_chain/chromadb_manager.py
  app/rag_lang_chain/google_cse_retriver.py
  app/rag_lang_chain/langchain_applied.py
  app/router/generate_simple_article_router.py
  app/service/news_scheduling_service.py
  app/service/simple_article_service.py
Labels: Enhancement

#94 UserTypes 순환참조 해결
  app/model/user_type.py
  app/repository/user_type_crud.py
  app/router/user_type_router.py
  app/service/user_type_service.py
Labels: Bug

#90 추천 시스템 스케줄링에서 버그 픽스
  app/model/interaction.py
  app/recommend/recommend_service.py
  app/service/news_scheduling_service.py
Labels: Bug

#95 필요 없는 라우터 제거
  app/main.py
  app/router/newsletter_article_crud_router.py
  app/router/subscription_crud_router.py
  app/router/user_type_router.py
Labels: Ship

#96 기사 긁어 올때 이미지, 발행일까지 추가
  app/model/article_model.py
  app/model/crawled_article.py
  app/service/article_manage_service.py
  app/service/crawl_article_service.py
  app/service/simple_article_service.py
Labels: Feature

#98 User type 관련 버그 픽스
  app/model/user_type.py
  app/service/user_type_service.py
Labels: Bug

#101 lightfm 주석처리
  Dockerfile
  Pipfile
  Pipfile.lock
  app/recommend/recommend_service.py
Labels: Ship

#89 Google CSE 키값 추가 배포
  .github/workflows/deploy-ecs.yml
  .pylintrc
  Dockerfile
  app/main.py
Labels: Ship

#104 action 파일 수정
  .github/workflows/deploy-ecs.yml
Labels: Ship

#102 지민이가 만든 RAG/LangChanin 활용하여 [경단챗봇 - 기사 API] 구현
  app/main.py
  app/router/__init__.py
  app/router/chatbot_article_detail_router.py
  app/service/chatbot_article_detail_service.py
Labels: Feature

#107 추천 시스템 implicit로 변경
  Pipfile
  Pipfile.lock
  app/model/recommend.py
  app/model/user_type.py
  app/recommend/recommend_service.py
  app/recommend/recommend_service_deactivate.py
  app/recommend/user_classification.csv
  app/repository/recommend_crud.py
  app/repository/user_type_crud.py
  app/service/news_scheduling_service.py
  app/service/user_type_service.py
Labels: Feature

#106 경단 챗봇 기사 API 리팩토링
  app/main.py
  app/router/chatbot_article_router.py
  app/service/chatbot_article_service.py
Labels: Feature

#113 implicit 버그 픽스
  Dockerfile
  Pipfile
  Pipfile.lock
  app/model/crawled_article.py
  app/model/prompt/simple_article/2024-07-14.txt
  app/model/subscription.py
  app/rag_lang_chain/langchain_applied.py
  app/recommend/__init__.py
  app/repository/crawled_article_crud.py
  app/service/article_manage_service.py
  app/service/news_scheduling_service.py
  app/service/simple_article_service.py
Labels: Bug

#117 Rag를 통해 생성되는 related_documents DB에 저장하기
  app/model/article_related_document.py
  app/model/crawled_article.py
  app/service/article_related_document_service.py
  app/service/simple_article_service.py
Labels: Feature

#116 추천시스템 라우터 리턴 값 변경
  app/model/crawled_article.py
  app/recommend/recommend_service.py
  app/repository/recommend_crud.py
  app/repository/user_type_crud.py
  app/router/user_type_router.py
  app/service/simple_article_service.py
  app/service/user_type_service.py
Labels: Feature

#122 헬스체크 추가
  app/main.py
Labels: Ship

#119 프롬프트 간단히 수정
  app/model/prompt/graphic_article/2024-07-10.txt
Labels: Ship

#128 CORS 설정
  app/main.py
Labels: Bug

#131 usertype 관련 API 수정
  app/router/user_type_router.py
  app/service/user_type_service.py
Labels: Enhancement, Bug

#133 유형검사 결과 return dto 수정
  app/model/user_type.py
  app/router/user_type_router.py
Labels: Enhancement, Feature

#135 유형검사 결과 똑같은 퍼센트가 있을 경우 대응
  app/model/user_type.py
Labels: Enhancement
