Repository Gyeongdan/gyeongdan-server-fastapi, pull requests merged in 2024-06, with the labels that each got.

#31 크롤링 후 DB 저장하는 로직 붙이기
  .pylintrc
  app/router/article_crud_router.py
  app/router/news_scrap_router.py
  app/service/crawl_article_service.py
  app/service/crawled_article_service.py
Labels: ship

#30 메일 송신 db 생성과 crud 기능 구현
  app/main.py
  app/model/newsletter_article.py
  app/repository/newsletter_article_crud.py
  app/router/newsletter_article_crud_router.py
  app/service/newsletter_article_service.py
Labels: feature

#35 뉴스레터용 table category enum으로 수정
  app/model/newsletter_article.py
  app/model/subscription.py
  app/repository/newsletter_article_crud.py
  app/repository/subscription_crud.py
  app/router/newsletter_article_crud_router.py
  app/router/subscription_crud_router.py
  app/service/newsletter_article_service.py
  app/service/subscription_service.py
Labels: feature

#36 기사 재생성 LLM 요청 프로토타입 #25
  .gitignore
  Pipfile
  Pipfile.lock
  app/main.py
  app/model/ai_client/get_platform_client.py
  app/model/ai_client/groq_client.py
  app/model/ai_client/openai_client.py
  app/model/crawled_article.py
  app/model/prompt/__init__.py
  app/model/prompt/prompt_version.py
  app/model/prompt/simple_article/2024-06-30.txt
  app/repository/crawled_article_crud.py
  app/router/article_crud_router.py
  app/router/generate_simple_article_router.py
  app/router/news_scrap_router.py
  app/service/article_manage_service.py
  app/service/crawl_article_service.py
  app/service/simple_article_service.py
Labels: feature, 👋 show my code
